export const EXPERIENCES = [
  {
    key: "paylivre_experience",
    title: "Dev BackendDev Backend",
    company: "Paylivre",
    period: "jul de 2022 - out de 2022 · 4 meses",
    location: "Barueri, São Paulo, Brazil",
    description: "Análise de dados pra auxilio resposta ao suporte. Desenvolvimento de features, criação de estrutura de projetos com projeto conectado à múltiplas databases (Services, actions, models, factory). Correção de problemas encontrados pelos clientes. Desenvolvimento via api com testes, dentre outros",
    competencies: [
      "GitFlow",
      "JIRA",
      "API REST",
      "Desenvolvimento de API",
      "Testes de API",
      "GitLab",
      "Arquitetura MVC",
      "Scrum",
      "Kanban",
      "Frameworks PHP",
      "Gestão",
      "Trabalho em equipe",
      "PHPUnit",
      "Desenvolvimento de back-end",
      "GitHub",
      "MySQL",
      "Git",
      "Laravel",
      "PHP",
      "Desenvolvimento web",
    ]
  },
  {
    key: "precpago_experience",
    title: "Programador de Sistemas de Informação",
    company: "PrecPago",
    period: "nov de 2021 - jul de 2022 · 9 meses",
    location: "Uberlândia, Minas Gerais, Brasil",
    description: "Desenvolvimento de novas features utilizando laravel, livewire, git, github, mysql. Corrigindo bugs nos sistemas em código já existenteDesenvolvimento de novas features utilizando laravel, livewire, git, github, mysql. Corrigindo bugs nos sistemas em código já existente",
    competencies: [
      "Arquitetura MVC",
      "Scrum",
      "Kanban",
      "Frameworks PHP",
      "Livewire",
      "Trabalho em equipe",
      "PHPUnit",
      "Desenvolvimento full stack",
      "Desenvolvimento de front-end",
      "Desenvolvimento de back-end",
      "GitHub",
      "MySQL",
      "Git",
      "Laravel",
      "PHP",
      "HTML",
      "Desenvolvimento web",
      "CSS",
    ]
  }
]